apiVersion: apps/v1
kind: Deployment

metadata:
  name: game-tracker
  namespace: emortalmc
  labels:
    app: game-tracker

spec:
  replicas: 3
  selector:
    matchLabels:
      app: game-tracker

  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: game-tracker
    spec:
      containers:
        - name: game-tracker
          image: ghcr.io/emortalmc/game-tracker:fa5653254189c4de1bc7cbc259e11ecfa5406e94
          ports:
            - name: grpc
              containerPort: 9010

          env:
            - name: "DEVELOPMENT"
              value: "false"
            - name: KAFKA_HOST
              value: default-kafka-bootstrap
            - name: KAFKA_PORT
              value: "9092"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: game-tracker-db-creds
                  key: connection-string
            - name: PORT
              value: "9010"